Installazione numpy

In [33]:
pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: /Users/acapodanno/PycharmProjects/JupyterProject/.venv/bin/python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


Import e creazione ndarray

In [34]:
import numpy as np

In [35]:
print(np.array([[1,2,3],[4,5,6]]))

[[1 2 3]
 [4 5 6]]


Operatori Numpy

In [36]:
a = np.random.randint(1,3,(3,4))
b = np.random.randint(1,3,(3,4))
c = np.random.randint(1,3,(3,4))

print(a)
print(b)
print(c)

[[1 1 2 2]
 [2 2 1 2]
 [1 2 2 1]]
[[2 1 1 2]
 [2 1 1 2]
 [2 2 1 2]]
[[2 2 2 2]
 [2 2 1 2]
 [1 2 2 1]]


Somma fra matrice

In [42]:
sum = a + b
print(sum)
#equivalente alla funzione add
print(np.add(a,b))

[[3 2 3 4]
 [4 3 2 4]
 [3 4 3 3]]
[[3 2 3 4]
 [4 3 2 4]
 [3 4 3 3]]


Differenza fra matrice

In [44]:
diff = a - b
print(diff)
#equivalente alla funzione subtract
print(np.subtract(a,b))

[[-1  0  1  0]
 [ 0  1  0  0]
 [-1  0  1 -1]]
[[-1  0  1  0]
 [ 0  1  0  0]
 [-1  0  1 -1]]


Operatore bit a bit

In [46]:
a ^ b
print(a ^ b)
print(a & b)
print(a | b)

[[3 0 3 0]
 [0 3 0 0]
 [3 0 3 3]]
[[0 1 0 2]
 [2 0 1 2]
 [0 2 0 0]]
[[3 1 3 2]
 [2 3 1 2]
 [3 2 3 3]]


Altre funzioni aritmetiche...

In [49]:
print(np.power(a,b))
print(np.sqrt(a))


[[1 1 2 4]
 [4 2 1 4]
 [1 4 2 1]]
[[1.         1.         1.41421356 1.41421356]
 [1.41421356 1.41421356 1.         1.41421356]
 [1.         1.41421356 1.41421356 1.        ]]
